apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bs6crfovy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bs6crfovy-python 
  name: bs6crfovy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bs6crfovy-python 
